Trade layout
gnosis/dex-react pull request #1404
Opened 2020-09-11 12:18 UTC by anxolin

Adds a new layout for the v2.0 so we can start shaping it. 
Maintains all the old routes, and creates new routes for `v2`:

![image](https://user-images.githubusercontent.com/2352112/92924658-9c406300-f439-11ea-8bb6-b7d5efa0f6cd.png)

2020-09-11 12:26 UTC, gnosis-info commented
Travis automatic deployment:
   * **🎩 [Dapp](https://pr1404--dexreact.review.gnosisdev.com)**: Testing web app
   * **📚 [Storybook](https://pr1404--dexreact.review.gnosisdev.com/storybook/)**: Component stories

2020-09-11 12:53 UTC, Velenir requested changes

2020-09-11 12:53 UTC, Velenir commented on src/App.tsx
> +                <Route path="" exact component={Trading} />
```suggestion
                <Route path="/v2" exact component={Trading} />
```
there are no relative routes in react-router v5, this one becomes a catch-all with `path=""`
You can look forward to [v6](https://reacttraining.com/blog/react-router-v6-pre/#relative-route-path-and-link-to) though

2020-09-14 13:47 UTC, Velenir approved these changes

2020-09-14 16:31 UTC, merged