Add timeout for fetching tokens
gnosis/dex-react pull request #1644
Opened 2020-11-28 09:50 UTC by anxolin

We've observed in two occasions now that some Metamask fails to resolve some promise for contract calls. First with the issue of SNX/sUSD proxy deprecation, yesterday with Ledger MM (not it seems it doesn't do that anymore).

When this happens, we neither get a success or an error.

Currently, if for one token, the promise is not resolved, the overall "fetch all balances" promise don't resolve either (uses `Promise.all`)

This PR introduces a timeout for fetching individual tokens for this extreme cases. It uses 10s, maybe it could be less. But theoretically promises should resolve one way or the other!

2020-11-28 09:58 UTC, gnosis-info commented
Travis automatic deployment:
   * **🎩 [Dapp](https://pr1644--dexreact.review.gnosisdev.com)**: Testing web app
   * **📚 [Storybook](https://pr1644--dexreact.review.gnosisdev.com/storybook/)**: Component stories

2020-11-30 09:40 UTC, Velenir requested changes
I understand that this was made to be a quicker-than-quick fix. I'll make a PR with improvements

2020-11-30 09:40 UTC, Velenir commented on src/utils/miscellaneous.ts
> +    }, time),
We already have `delay()` util to do that

2020-11-30 09:40 UTC, Velenir commented on src/utils/miscellaneous.ts
> +export function timeout<T>(params: TimeoutParams<T>): Promise<T> {
Types are not exactly correct. You intentionally throw (return rejected Promise) for some `T`. Typescript can detect that if you do an overload type, for example

2020-11-30 09:40 UTC, Velenir commented on src/hooks/useTokenBalances.ts
> +    const timeoutPromise = timeout<TokenBalanceDetails | null>({
But this isn't `Promise<TokenBalanceDetails | null>`, this is `Promise<never>` as it will throw, always.

2020-11-30 09:40 UTC, Velenir commented on src/hooks/useTokenBalances.ts
>    return balances.filter(Boolean) as TokenBalanceDetails[]
We don't have to cast if we use a type-guard predicate `notEmpty`, which you made precisely for these cases, didn't you?

2020-11-30 09:40 UTC, Velenir commented on src/hooks/useTokenBalances.ts
> +      const cacheKey = constructCacheKey({ token, userAddress, contractAddress, networkId })
No real need to have `constructCacheKey(...)` in two places

2020-11-30 11:40 UTC, W3stside approved these changes

2020-11-30 15:54 UTC, merged